### ISSUE TITLE
How do I compile/run any code/project (x86)?

### ISSUE THREAD

**Issue by Ilir-Liburn** [ELENA-LANG/elena-lang#579] opened 2023-06-18 10:54 UTC
Hello,

I'm trying to compile&run examples60 using CLI or IDE (x86), but I'm getting

internal error 600: command set is not defined for 0
Compiled with errors

 - OS: [Windows 10 Pro x64]
 - Version [ELENA 6.0.3b]

**Comment by bencz** [comment] 2023-06-18 15:12
the bin folder, is it in the %path% of windows?

You can do this:
* open CMD
* navigate to the bin folder of the ELENA project
* type: PATH=%CD%;%PATH%
* open IDE using the CMD, type: elena-ide.exe
* open the project
* build it
* run it

To run a ELENA generate EXE, it's necessary to have the bin folder on %PATH%

**Comment by Ilir-Liburn** [comment] 2023-06-18 15:48
Hello,

of course it is in a path. You missed error message?

internal error 600: command set is not defined for 0
Compiled with errors

**Comment by arakov** [comment] 2023-06-18 19:38
Hi, unfortunately several files were missed in the released archive.  I've fixed it. Please try to unpack the attached archive
[elena-lang.6.0.3b.x86-64-win.zip](https://github.com/ELENA-LANG/elena-lang/files/11782443/elena-lang.6.0.3b.x86-64-win.zip)

Let me know if the issue is resolved

**Comment by Ilir-Liburn** [comment] 2023-06-18 20:11
Hello,

Yes, that solved the issue, bot 32 and 64 bit versions are working now.

Thank you

**Comment by arakov** [comment] 2023-06-18 20:16
closing per the comment above

**Closed by arakov** 2023-06-18 20:16 UTC
Labels: bug
